/* tslint:disable */
/* eslint-disable */
/**
 * CVCreationPlatform.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * EducationApi - axios parameter creator
 * @export
 */
export const EducationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} educationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEducationEducationsEducationIdDelete: async (educationId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'educationId' is not null or undefined
            if (educationId === null || educationId === undefined) {
                throw new RequiredError('educationId','Required parameter educationId was null or undefined when calling apiEducationEducationsEducationIdDelete.');
            }
            const localVarPath = `/api/Education/educations/{educationId}`
                .replace(`{${"educationId"}}`, encodeURIComponent(String(educationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} educationId 
         * @param {string} [instituteName] 
         * @param {string} [degree] 
         * @param {string} [fieldOfStudy] 
         * @param {string} [startDate] 
         * @param {string} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEducationEducationsEducationIdPutForm: async (educationId: number, instituteName?: string, degree?: string, fieldOfStudy?: string, startDate?: string, endDate?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'educationId' is not null or undefined
            if (educationId === null || educationId === undefined) {
                throw new RequiredError('educationId','Required parameter educationId was null or undefined when calling apiEducationEducationsEducationIdPutForm.');
            }
            const localVarPath = `/api/Education/educations/{educationId}`
                .replace(`{${"educationId"}}`, encodeURIComponent(String(educationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication oauth2 required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }


            if (instituteName !== undefined) { 
                localVarFormParams.append('InstituteName', instituteName as any);
            }

            if (degree !== undefined) { 
                localVarFormParams.append('Degree', degree as any);
            }

            if (fieldOfStudy !== undefined) { 
                localVarFormParams.append('FieldOfStudy', fieldOfStudy as any);
            }

            if (startDate !== undefined) { 
                localVarFormParams.append('StartDate', startDate as any);
            }

            if (endDate !== undefined) { 
                localVarFormParams.append('EndDate', endDate as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} resumeId 
         * @param {string} [instituteName] 
         * @param {string} [degree] 
         * @param {string} [fieldOfStudy] 
         * @param {string} [startDate] 
         * @param {string} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEducationEducationsResumeIdPostForm: async (resumeId: string, instituteName?: string, degree?: string, fieldOfStudy?: string, startDate?: string, endDate?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resumeId' is not null or undefined
            if (resumeId === null || resumeId === undefined) {
                throw new RequiredError('resumeId','Required parameter resumeId was null or undefined when calling apiEducationEducationsResumeIdPostForm.');
            }
            const localVarPath = `/api/Education/educations/{resumeId}`
                .replace(`{${"resumeId"}}`, encodeURIComponent(String(resumeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication oauth2 required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }


            if (instituteName !== undefined) { 
                localVarFormParams.append('InstituteName', instituteName as any);
            }

            if (degree !== undefined) { 
                localVarFormParams.append('Degree', degree as any);
            }

            if (fieldOfStudy !== undefined) { 
                localVarFormParams.append('FieldOfStudy', fieldOfStudy as any);
            }

            if (startDate !== undefined) { 
                localVarFormParams.append('StartDate', startDate as any);
            }

            if (endDate !== undefined) { 
                localVarFormParams.append('EndDate', endDate as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EducationApi - functional programming interface
 * @export
 */
export const EducationApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} educationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationEducationsEducationIdDelete(educationId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await EducationApiAxiosParamCreator(configuration).apiEducationEducationsEducationIdDelete(educationId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {number} educationId 
         * @param {string} [instituteName] 
         * @param {string} [degree] 
         * @param {string} [fieldOfStudy] 
         * @param {string} [startDate] 
         * @param {string} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationEducationsEducationIdPutForm(educationId: number, instituteName?: string, degree?: string, fieldOfStudy?: string, startDate?: string, endDate?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await EducationApiAxiosParamCreator(configuration).apiEducationEducationsEducationIdPutForm(educationId, instituteName, degree, fieldOfStudy, startDate, endDate, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} resumeId 
         * @param {string} [instituteName] 
         * @param {string} [degree] 
         * @param {string} [fieldOfStudy] 
         * @param {string} [startDate] 
         * @param {string} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationEducationsResumeIdPostForm(resumeId: string, instituteName?: string, degree?: string, fieldOfStudy?: string, startDate?: string, endDate?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await EducationApiAxiosParamCreator(configuration).apiEducationEducationsResumeIdPostForm(resumeId, instituteName, degree, fieldOfStudy, startDate, endDate, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * EducationApi - factory interface
 * @export
 */
export const EducationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {number} educationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationEducationsEducationIdDelete(educationId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return EducationApiFp(configuration).apiEducationEducationsEducationIdDelete(educationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} educationId 
         * @param {string} [instituteName] 
         * @param {string} [degree] 
         * @param {string} [fieldOfStudy] 
         * @param {string} [startDate] 
         * @param {string} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationEducationsEducationIdPutForm(educationId: number, instituteName?: string, degree?: string, fieldOfStudy?: string, startDate?: string, endDate?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return EducationApiFp(configuration).apiEducationEducationsEducationIdPutForm(educationId, instituteName, degree, fieldOfStudy, startDate, endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} resumeId 
         * @param {string} [instituteName] 
         * @param {string} [degree] 
         * @param {string} [fieldOfStudy] 
         * @param {string} [startDate] 
         * @param {string} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationEducationsResumeIdPostForm(resumeId: string, instituteName?: string, degree?: string, fieldOfStudy?: string, startDate?: string, endDate?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return EducationApiFp(configuration).apiEducationEducationsResumeIdPostForm(resumeId, instituteName, degree, fieldOfStudy, startDate, endDate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EducationApi - object-oriented interface
 * @export
 * @class EducationApi
 * @extends {BaseAPI}
 */
export class EducationApi extends BaseAPI {
    /**
     * 
     * @param {number} educationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EducationApi
     */
    public async apiEducationEducationsEducationIdDelete(educationId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return EducationApiFp(this.configuration).apiEducationEducationsEducationIdDelete(educationId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {number} educationId 
     * @param {string} [instituteName] 
     * @param {string} [degree] 
     * @param {string} [fieldOfStudy] 
     * @param {string} [startDate] 
     * @param {string} [endDate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EducationApi
     */
    public async apiEducationEducationsEducationIdPutForm(educationId: number, instituteName?: string, degree?: string, fieldOfStudy?: string, startDate?: string, endDate?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return EducationApiFp(this.configuration).apiEducationEducationsEducationIdPutForm(educationId, instituteName, degree, fieldOfStudy, startDate, endDate, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} resumeId 
     * @param {string} [instituteName] 
     * @param {string} [degree] 
     * @param {string} [fieldOfStudy] 
     * @param {string} [startDate] 
     * @param {string} [endDate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EducationApi
     */
    public async apiEducationEducationsResumeIdPostForm(resumeId: string, instituteName?: string, degree?: string, fieldOfStudy?: string, startDate?: string, endDate?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return EducationApiFp(this.configuration).apiEducationEducationsResumeIdPostForm(resumeId, instituteName, degree, fieldOfStudy, startDate, endDate, options).then((request) => request(this.axios, this.basePath));
    }
}
