/* tslint:disable */
/* eslint-disable */
/**
 * CVCreationPlatform.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { type AxiosResponse, type AxiosInstance, type AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * LanguageApi - axios parameter creator
 * @export
 */
export const LanguageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} languageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLanguageLanguagesLanguageIdDelete: async (languageId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'languageId' is not null or undefined
            if (languageId === null || languageId === undefined) {
                throw new RequiredError('languageId','Required parameter languageId was null or undefined when calling apiLanguageLanguagesLanguageIdDelete.');
            }
            const localVarPath = `/api/Language/languages/{languageId}`
                .replace(`{${"languageId"}}`, encodeURIComponent(String(languageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} languageId 
         * @param {string} [name] 
         * @param {string} [level] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLanguageLanguagesLanguageIdPutForm: async (languageId: number, name?: string, level?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'languageId' is not null or undefined
            if (languageId === null || languageId === undefined) {
                throw new RequiredError('languageId','Required parameter languageId was null or undefined when calling apiLanguageLanguagesLanguageIdPutForm.');
            }
            const localVarPath = `/api/Language/languages/{languageId}`
                .replace(`{${"languageId"}}`, encodeURIComponent(String(languageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication oauth2 required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }


            if (name !== undefined) { 
                localVarFormParams.append('Name', name as any);
            }

            if (level !== undefined) { 
                localVarFormParams.append('Level', level as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} resumeId 
         * @param {string} [name] 
         * @param {string} [level] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLanguageLanguagesResumeIdPostForm: async (resumeId: string, name?: string, level?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resumeId' is not null or undefined
            if (resumeId === null || resumeId === undefined) {
                throw new RequiredError('resumeId','Required parameter resumeId was null or undefined when calling apiLanguageLanguagesResumeIdPostForm.');
            }
            const localVarPath = `/api/Language/languages/{resumeId}`
                .replace(`{${"resumeId"}}`, encodeURIComponent(String(resumeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication oauth2 required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }


            if (name !== undefined) { 
                localVarFormParams.append('Name', name as any);
            }

            if (level !== undefined) { 
                localVarFormParams.append('Level', level as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LanguageApi - functional programming interface
 * @export
 */
export const LanguageApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} languageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLanguageLanguagesLanguageIdDelete(languageId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await LanguageApiAxiosParamCreator(configuration).apiLanguageLanguagesLanguageIdDelete(languageId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {number} languageId 
         * @param {string} [name] 
         * @param {string} [level] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLanguageLanguagesLanguageIdPutForm(languageId: number, name?: string, level?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await LanguageApiAxiosParamCreator(configuration).apiLanguageLanguagesLanguageIdPutForm(languageId, name, level, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} resumeId 
         * @param {string} [name] 
         * @param {string} [level] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLanguageLanguagesResumeIdPostForm(resumeId: string, name?: string, level?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await LanguageApiAxiosParamCreator(configuration).apiLanguageLanguagesResumeIdPostForm(resumeId, name, level, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * LanguageApi - factory interface
 * @export
 */
export const LanguageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {number} languageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLanguageLanguagesLanguageIdDelete(languageId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return LanguageApiFp(configuration).apiLanguageLanguagesLanguageIdDelete(languageId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} languageId 
         * @param {string} [name] 
         * @param {string} [level] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLanguageLanguagesLanguageIdPutForm(languageId: number, name?: string, level?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return LanguageApiFp(configuration).apiLanguageLanguagesLanguageIdPutForm(languageId, name, level, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} resumeId 
         * @param {string} [name] 
         * @param {string} [level] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLanguageLanguagesResumeIdPostForm(resumeId: string, name?: string, level?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return LanguageApiFp(configuration).apiLanguageLanguagesResumeIdPostForm(resumeId, name, level, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LanguageApi - object-oriented interface
 * @export
 * @class LanguageApi
 * @extends {BaseAPI}
 */
export class LanguageApi extends BaseAPI {
    /**
     * 
     * @param {number} languageId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LanguageApi
     */
    public async apiLanguageLanguagesLanguageIdDelete(languageId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return LanguageApiFp(this.configuration).apiLanguageLanguagesLanguageIdDelete(languageId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {number} languageId 
     * @param {string} [name] 
     * @param {string} [level] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LanguageApi
     */
    public async apiLanguageLanguagesLanguageIdPutForm(languageId: number, name?: string, level?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return LanguageApiFp(this.configuration).apiLanguageLanguagesLanguageIdPutForm(languageId, name, level, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} resumeId 
     * @param {string} [name] 
     * @param {string} [level] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LanguageApi
     */
    public async apiLanguageLanguagesResumeIdPostForm(resumeId: string, name?: string, level?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return LanguageApiFp(this.configuration).apiLanguageLanguagesResumeIdPostForm(resumeId, name, level, options).then((request) => request(this.axios, this.basePath));
    }
}
