/* tslint:disable */
/* eslint-disable */
/**
 * CVCreationPlatform.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * RecommendationApi - axios parameter creator
 * @export
 */
export const RecommendationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} resumeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiRecommendationFeedbackResumeIdPost: async (resumeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resumeId' is not null or undefined
            if (resumeId === null || resumeId === undefined) {
                throw new RequiredError('resumeId','Required parameter resumeId was null or undefined when calling apiRecommendationFeedbackResumeIdPost.');
            }
            const localVarPath = `/api/Recommendation/feedback/{resumeId}`
                .replace(`{${"resumeId"}}`, encodeURIComponent(String(resumeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [text] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiRecommendationRecommendationsPost: async (text?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Recommendation/recommendations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (text !== undefined) {
                localVarQueryParameter['text'] = text;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecommendationApi - functional programming interface
 * @export
 */
export const RecommendationApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} resumeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiRecommendationFeedbackResumeIdPost(resumeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await RecommendationApiAxiosParamCreator(configuration).apiRecommendationFeedbackResumeIdPost(resumeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} [text] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiRecommendationRecommendationsPost(text?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await RecommendationApiAxiosParamCreator(configuration).apiRecommendationRecommendationsPost(text, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * RecommendationApi - factory interface
 * @export
 */
export const RecommendationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} resumeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiRecommendationFeedbackResumeIdPost(resumeId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return RecommendationApiFp(configuration).apiRecommendationFeedbackResumeIdPost(resumeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [text] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiRecommendationRecommendationsPost(text?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return RecommendationApiFp(configuration).apiRecommendationRecommendationsPost(text, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecommendationApi - object-oriented interface
 * @export
 * @class RecommendationApi
 * @extends {BaseAPI}
 */
export class RecommendationApi extends BaseAPI {
    /**
     * 
     * @param {string} resumeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationApi
     */
    public async apiRecommendationFeedbackResumeIdPost(resumeId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return RecommendationApiFp(this.configuration).apiRecommendationFeedbackResumeIdPost(resumeId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} [text] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationApi
     */
    public async apiRecommendationRecommendationsPost(text?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return RecommendationApiFp(this.configuration).apiRecommendationRecommendationsPost(text, options).then((request) => request(this.axios, this.basePath));
    }
}
