/* tslint:disable */
/* eslint-disable */
/**
 * CVCreationPlatform.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CertificateDTO
 */
export interface CertificateDTO {
    /**
     * 
     * @type {string}
     * @memberof CertificateDTO
     */
    certificateName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CertificateDTO
     */
    issuingOrganization?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CertificateDTO
     */
    issueDate?: Date | null;
}
