/* tslint:disable */
/* eslint-disable */
/**
 * CVCreationPlatform.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CertificatesResumeIdBody
 */
export interface CertificatesResumeIdBody {
    /**
     * 
     * @type {string}
     * @memberof CertificatesResumeIdBody
     */
    certificateName?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificatesResumeIdBody
     */
    issuingOrganization?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificatesResumeIdBody
     */
    issueDate?: string;
}
