/* tslint:disable */
/* eslint-disable */
/**
 * CVCreationPlatform.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EducationsEducationIdBody
 */
export interface EducationsEducationIdBody {
    /**
     * 
     * @type {string}
     * @memberof EducationsEducationIdBody
     */
    instituteName?: string;
    /**
     * 
     * @type {string}
     * @memberof EducationsEducationIdBody
     */
    degree?: string;
    /**
     * 
     * @type {string}
     * @memberof EducationsEducationIdBody
     */
    fieldOfStudy?: string;
    /**
     * 
     * @type {string}
     * @memberof EducationsEducationIdBody
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof EducationsEducationIdBody
     */
    endDate?: string;
}
