/* tslint:disable */
/* eslint-disable */
/**
 * CVCreationPlatform.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LanguageVM
 */
export interface LanguageVM {
    /**
     * 
     * @type {number}
     * @memberof LanguageVM
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LanguageVM
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LanguageVM
     */
    level?: string | null;
}
