/* tslint:disable */
/* eslint-disable */
/**
 * CVCreationPlatform.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PersonalInfoDTO
 */
export interface PersonalInfoDTO {
    /**
     * 
     * @type {Blob}
     * @memberof PersonalInfoDTO
     */
    photo?: Blob | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoDTO
     */
    photoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoDTO
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoDTO
     */
    middleName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoDTO
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoDTO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoDTO
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoDTO
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoDTO
     */
    email?: string | null;
}
