/* tslint:disable */
/* eslint-disable */
/**
 * CVCreationPlatform.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ResumesShareBody
 */
export interface ResumesShareBody {
    /**
     * 
     * @type {string}
     * @memberof ResumesShareBody
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof ResumesShareBody
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof ResumesShareBody
     */
    receiptantEmail?: string;
    /**
     * 
     * @type {Blob}
     * @memberof ResumesShareBody
     */
    file?: Blob;
}
