/* tslint:disable */
/* eslint-disable */
/**
 * CVCreationPlatform.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { type CertificateDTO } from './certificate-dto';
import { type EducationDTO } from './education-dto';
import { type LanguageDTO } from './language-dto';
import { type PersonalInfoDTO } from './personal-info-dto';
import { type SkillsDTO } from './skills-dto';
import { type TemplateDTO } from './template-dto';
import { type UnknownSectionDTO } from './unknown-section-dto';
import { type WorkExperienceDTO } from './work-experience-dto';
/**
 * 
 * @export
 * @interface ResumeDTO
 */
export interface ResumeDTO {
    /**
     * 
     * @type {string}
     * @memberof ResumeDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ResumeDTO
     */
    title?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ResumeDTO
     */
    creationDate?: Date;
    /**
     * 
     * @type {PersonalInfoDTO}
     * @memberof ResumeDTO
     */
    personalInfo?: PersonalInfoDTO;
    /**
     * 
     * @type {UnknownSectionDTO}
     * @memberof ResumeDTO
     */
    unknownSection?: UnknownSectionDTO;
    /**
     * 
     * @type {TemplateDTO}
     * @memberof ResumeDTO
     */
    template?: TemplateDTO;
    /**
     * 
     * @type {Array<CertificateDTO>}
     * @memberof ResumeDTO
     */
    certificates?: Array<CertificateDTO> | null;
    /**
     * 
     * @type {Array<EducationDTO>}
     * @memberof ResumeDTO
     */
    educations?: Array<EducationDTO> | null;
    /**
     * 
     * @type {Array<WorkExperienceDTO>}
     * @memberof ResumeDTO
     */
    workExperiences?: Array<WorkExperienceDTO> | null;
    /**
     * 
     * @type {Array<LanguageDTO>}
     * @memberof ResumeDTO
     */
    languages?: Array<LanguageDTO> | null;
    /**
     * 
     * @type {Array<SkillsDTO>}
     * @memberof ResumeDTO
     */
    skills?: Array<SkillsDTO> | null;
}
