/* tslint:disable */
/* eslint-disable */
/**
 * CVCreationPlatform.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CertificateVM } from './certificate-vm';
import { EducationVM } from './education-vm';
import { LanguageVM } from './language-vm';
import { PersonalInfoVM } from './personal-info-vm';
import { SkillVM } from './skill-vm';
import { TemplateVM } from './template-vm';
import { UnknownSectionVM } from './unknown-section-vm';
import { WorkExperienceVM } from './work-experience-vm';
/**
 * 
 * @export
 * @interface ResumeVM
 */
export interface ResumeVM {
    /**
     * 
     * @type {string}
     * @memberof ResumeVM
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResumeVM
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ResumeVM
     */
    title?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ResumeVM
     */
    creationDate?: Date;
    /**
     * 
     * @type {PersonalInfoVM}
     * @memberof ResumeVM
     */
    personalInfo?: PersonalInfoVM;
    /**
     * 
     * @type {UnknownSectionVM}
     * @memberof ResumeVM
     */
    unknownSection?: UnknownSectionVM;
    /**
     * 
     * @type {TemplateVM}
     * @memberof ResumeVM
     */
    template?: TemplateVM;
    /**
     * 
     * @type {Array<CertificateVM>}
     * @memberof ResumeVM
     */
    certificates?: Array<CertificateVM> | null;
    /**
     * 
     * @type {Array<EducationVM>}
     * @memberof ResumeVM
     */
    educations?: Array<EducationVM> | null;
    /**
     * 
     * @type {Array<WorkExperienceVM>}
     * @memberof ResumeVM
     */
    workExperiences?: Array<WorkExperienceVM> | null;
    /**
     * 
     * @type {Array<LanguageVM>}
     * @memberof ResumeVM
     */
    languages?: Array<LanguageVM> | null;
    /**
     * 
     * @type {Array<SkillVM>}
     * @memberof ResumeVM
     */
    skills?: Array<SkillVM> | null;
}
