/* tslint:disable */
/* eslint-disable */
/**
 * CVCreationPlatform.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WorkExperiencesWorkExperienceIdBody
 */
export interface WorkExperiencesWorkExperienceIdBody {
    /**
     * 
     * @type {string}
     * @memberof WorkExperiencesWorkExperienceIdBody
     */
    companyName?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkExperiencesWorkExperienceIdBody
     */
    position?: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkExperiencesWorkExperienceIdBody
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkExperiencesWorkExperienceIdBody
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof WorkExperiencesWorkExperienceIdBody
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkExperiencesWorkExperienceIdBody
     */
    description?: string;
}
