/* tslint:disable */
/* eslint-disable */
/**
 * CVCreationPlatform.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WorkExperienceDTO
 */
export interface WorkExperienceDTO {
    /**
     * 
     * @type {string}
     * @memberof WorkExperienceDTO
     */
    companyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkExperienceDTO
     */
    position?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof WorkExperienceDTO
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof WorkExperienceDTO
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof WorkExperienceDTO
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkExperienceDTO
     */
    description?: string | null;
}
